mkdir -p /hyperfile/volumes/123/123_1/gigi
cd /hyperfile/volumes/123/123_1/gigi
echo "(1/16) testing chmod..."
prove -rv /root/hyperfile4/pjdfstest/tests/chmod &>/root/hyperfile4/pjdfstest/reports/chmod.txt
echo "(2/16) testing chown..."
prove -rv /root/hyperfile4/pjdfstest/tests/chown &>/root/hyperfile4/pjdfstest/reports/chown.txt
echo "(3/16) testing ftruncate..."
prove -rv /root/hyperfile4/pjdfstest/tests/ftruncate &>/root/hyperfile4/pjdfstest/reports/ftruncate.txt
echo "(4/16) testing granular..."
prove -rv /root/hyperfile4/pjdfstest/tests/granular &>/root/hyperfile4/pjdfstest/reports/granular.txt
echo "(5/16) testing link..."
prove -rv /root/hyperfile4/pjdfstest/tests/link &>/root/hyperfile4/pjdfstest/reports/link.txt
echo "(6/16) testing mkdir..."
prove -rv /root/hyperfile4/pjdfstest/tests/mkdir &>/root/hyperfile4/pjdfstest/reports/mkdir.txt
echo "(7/16) testing mknod..."
prove -rv /root/hyperfile4/pjdfstest/tests/mknod &>/root/hyperfile4/pjdfstest/reports/mknod.txt
echo "(8/16) testing posix_fallocate..."
prove -rv /root/hyperfile4/pjdfstest/tests/posix_fallocate &>/root/hyperfile4/pjdfstest/reports/posix_fallocate.txt
echo "(9/16) testing open..."
prove -rv /root/hyperfile4/pjdfstest/tests/open &>/root/hyperfile4/pjdfstest/reports/open.txt
echo "(10/16) testing rename..."
prove -rv /root/hyperfile4/pjdfstest/tests/rename &>/root/hyperfile4/pjdfstest/reports/rename.txt
echo "(11/16) testing rmdir..."
prove -rv /root/hyperfile4/pjdfstest/tests/rmdir &>/root/hyperfile4/pjdfstest/reports/rmdir.txt
echo "(12/16) testing truncate..."
prove -rv /root/hyperfile4/pjdfstest/tests/truncate &>/root/hyperfile4/pjdfstest/reports/truncate.txt
echo "(13/16) testing symlink..."
prove -rv /root/hyperfile4/pjdfstest/tests/symlink &>/root/hyperfile4/pjdfstest/reports/symlink.txt
echo "(14/16) testing utimensat..."
prove -rv /root/hyperfile4/pjdfstest/tests/utimensat &>/root/hyperfile4/pjdfstest/reports/utimensat.txt
echo "(15/16) testing unlink..."
prove -rv /root/hyperfile4/pjdfstest/tests/unlink &>/root/hyperfile4/pjdfstest/reports/unlink.txt
echo "(16/16) testing chflags..."
prove -rv /root/hyperfile4/pjdfstest/tests/chflags &>/root/hyperfile4/pjdfstest/reports/chflags.txt
